KRDS-community/krds-react

- packages/core/lib/components/Link.tsx
It should be `LinkProps`. I fixed the typo
> fix: label prop typo

- README.md
- packages/core/README.md
I updated main README.md and packages/core/README.md
> Doc: update README.md

- .gitignore
- .storybook/main.ts
- .storybook/preview.ts
- README.md
- package.json
- pnpm-lock.yaml
- stories/core/Body.stories.ts
- stories/core/Detail.stories.ts
- stories/core/Display.stories.ts
- stories/core/Heading.stories.ts
- stories/core/Label.stories.ts
- stories/core/Link.stories.ts
- stories/core/Title.stories.ts
It closes #3 
I added storybook in the root of project. and I added typography components in storybook.
> feat: add storybook

- .github/workflows/storybook.yaml
- .gitignore
I added storybook gh page. And I also set up the repo setting :)
> ci: add storybook gh page

- README.md
- stories/Introduction.mdx
It closes #31 #29 
I added intro mdx file in storybook and edit README about versioning.
> doc: add storybook intro

- CNAME
Add CNAME file for [js.org](https://js.org/)
> feat: add cname for krds.js.org

- stories/Introduction.mdx
I removed the code section. It's not implemented
> doc: fix code description in intro of storybook

- stories/Introduction.mdx
fix mdx syntax in intro of storybook
> doc: fix intro mdx syntax

- stories/core/Body.stories.ts
- stories/core/Detail.stories.ts
- stories/core/Display.stories.ts
- stories/core/Heading.stories.ts
- stories/core/Label.stories.ts
- stories/core/Link.stories.ts
- stories/core/Title.stories.ts
- stories/installation.mdx
README에 있는 정보들을 스토리북에 옮겼습니다. 컬러를 추가한 뒤 readme를 수정해둘게요.
> doc: integrate storybook docs

- packages/core/lib/components/Button.tsx
- packages/core/lib/index.ts
- stories/core/Button.stories.ts
I added button components
It closes #26
> feat: add button component

- packages/core/lib/components/LinkButton.tsx
- packages/core/lib/index.ts
- stories/core/LinkButton.stories.ts
It closes #36 
I added link button.
> feat: add link button

- packages/core/lib/components/Tag.tsx
- packages/core/lib/index.ts
- stories/core/Tag.stories.ts
It closes #65
I added a tag component
> feat: add tag component

- packages/core/lib/components/Spinner.tsx
- packages/core/lib/index.ts
- stories/core/Spinner.stories.ts
It closes #67 
I added a spinner component
> feat: add spinner

- packages/core/lib/components/Badge.tsx
- packages/core/lib/index.ts
- stories/core/Badge.stories.ts
It closes #56 
I added badge component
> feat: add badge component

- packages/core/lib/components/TextInput.tsx
- packages/core/lib/index.ts
- stories/core/TextInput.stories.ts
It closes #70 
I added a textInput component
> feat: add textInput component

- packages/core/lib/components/TextArea.tsx
- packages/core/lib/index.ts
- stories/core/TextArea.stories.ts
It closes #69 
I added a textArea component
> feat: add textArea component

- examples/core/src/App.tsx
- packages/core/lib/components/Checkbox.tsx
- packages/core/lib/components/Chip.tsx
- packages/core/lib/components/RadioButton.tsx
- packages/core/lib/components/Switch.tsx
- packages/core/lib/index.ts
- stories/core/Checkbox.stories.ts
- stories/core/Chip.stories.ts
- stories/core/RadioButton.stories.ts
- stories/core/Switch.stories.ts
It closes #62, #63 
I added
- switch
- chip
- checkbox
- radio
> feat: add checkbox and radioButton

- packages/core/lib/components/Tab.tsx
- packages/core/lib/index.ts
- stories/core/Tab.stories.tsx
It closes #60 
I added the tab component.
> feat: add tab component

- packages/core/lib/components/Accordion.tsx
- packages/core/lib/components/Disclosure.tsx
- packages/core/lib/index.ts
- stories/core/Accordion.stories.ts
- stories/core/Disclosure.stories.ts
It closes #57 
I added the accordion component
> feat: add accordion component

- packages/core/lib/components/FileUpload.tsx
- packages/core/lib/index.ts
- stories/core/FileUpload.stories.ts
> feat: add fileUpload component

- README.md
Figma files are added in README
> doc: add figma links

- .prettierignore
Fix issues that prettier checks build ouput files
> chore: prettier ignores build output

- packages/tailwindcss-plugin/README.md
- packages/tailwindcss-plugin/krds-plugin.js
I added breakpoints in out tailwindcss plugin.
It closes #98.
> feat: add breakpoints in tailwindcss plugin

- packages/core/lib/components/Calendar.tsx
- stories/core/Calendar.stories.ts
It closes #104
I added two new optional props
- minYear
- maxYear
> feat: fix year options bug in Calendar component

- README.md
- packages/core/README.md
개별 컴포넌트 지원 언급 삭제 및 storybook 언급 추가
> doc: edit feature in readme
